#!/usr/bin/env python3
"""
Generate color emoji images for the LVGL emoji picker.
Extracts embedded PNG bitmaps from NotoColorEmoji.ttf (CBDT table),
decodes with PIL, resizes to 20x20, and outputs LVGL RGBA8888 C arrays
with correct BGRA byte order (matching lv_color32_t memory layout).
"""
import struct
import sys
from pathlib import Path
from io import BytesIO
from fontTools.ttLib import TTFont
from PIL import Image

# The 52 emoji from the picker, in order
PICKER_EMOJI = [
    # Faces
    "\U0001F600", "\U0001F601", "\U0001F602", "\U0001F603",
    "\U0001F923", "\U0001F60A", "\U0001F60D", "\U0001F60E",
    "\U0001F914", "\U0001F60F", "\U0001F62E", "\U0001F622",
    "\U0001F62D", "\U0001F624", "\U0001F621", "\U0001F970",
    # Hands
    "\U0001F44D", "\U0001F44E", "\U0001F44C", "\u270C",
    "\U0001F44F", "\U0001F64C", "\U0001F64F", "\U0001F4AA",
    "\U0001F91D", "\U0001F44B",
    # Hearts
    "\u2764", "\U0001F9E1", "\U0001F49B", "\U0001F49A",
    "\U0001F499", "\U0001F49C", "\U0001F5A4", "\U0001F495",
    "\U0001F49E", "\U0001F493",
    # Objects/Symbols
    "\U0001F525", "\U0001F389", "\U0001F38A", "\u2705",
    "\u274C", "\U0001F4AF", "\u2B50", "\U0001F680",
    "\U0001F388", "\U0001F4A1", "\U0001F514", "\U0001F3AF",
    "\U0001F50B", "\u2699", "\U0001F4E1", "\U0001F30D",
]


def load_font():
    """Load NotoColorEmoji and return (font, cmap, strike_data)."""
    font_paths = [
        '/usr/share/fonts/truetype/noto/NotoColorEmoji.ttf',
        '/tmp/NotoColorEmoji.ttf',
    ]
    fp = None
    for p in font_paths:
        if Path(p).exists():
            fp = p
            break
    if not fp:
        print("ERROR: NotoColorEmoji.ttf not found", file=sys.stderr)
        sys.exit(1)

    font = TTFont(fp)
    cmap = font.getBestCmap()
    strike = font['CBDT'].strikeData[0]
    return font, cmap, strike


def extract_bitmap(cmap, strike, cp, target_size=20):
    """Extract embedded PNG bitmap for a codepoint, decode, resize to target_size.

    Returns raw bytes in BGRA order (matches lv_color32_t memory layout).
    """
    glyph = cmap.get(cp)
    if not glyph or glyph not in strike:
        return None

    png = strike[glyph].imageData
    if not png.startswith(b'\x89PNG'):
        return None

    img = Image.open(BytesIO(png)).convert('RGBA')
    img = img.resize((target_size, target_size), Image.Resampling.LANCZOS)

    # LVGL lv_color32_t stores bytes as: blue, green, red, alpha
    # PIL tobytes('raw', 'RGBA') produces: red, green, blue, alpha
    # So we use 'BGRA' to swap red/blue
    return img.tobytes('raw', 'BGRA')


def generate_lvgl_image_c(name, bgra_data, width, height):
    """Generate C source for an LVGL image resource."""
    assert len(bgra_data) == width * height * 4

    lines = [
        f'// LVGL image: {name} ({width}x{height} ARGB8888, BGRA byte order)',
        f'static const uint8_t {name}_data[] = {{',
    ]

    # Format as hex bytes, 16 per line
    for i in range(0, len(bgra_data), 16):
        chunk = bgra_data[i:i+16]
        hex_str = ', '.join(f'0x{b:02x}' for b in chunk)
        lines.append(f'    {hex_str},')

    lines.extend([
        '};',
        '',
        f'static const lv_image_dsc_t {name} = {{',
        f'    .header = {{',
        f'        .magic = LV_IMAGE_HEADER_MAGIC,',
        f'        .cf = LV_COLOR_FORMAT_ARGB8888,',
        f'        .flags = 0,',
        f'        .w = {width},',
        f'        .h = {height},',
        f'        .stride = {width} * 4,',
        f'        .reserved_2 = 0,',
        f'    }},',
        f'    .data_size = sizeof({name}_data),',
        f'    .data = {name}_data,',
        f'    .reserved = NULL,',
        f'    .reserved_2 = NULL,',
        f'}};',
        '',
    ])

    return '\n'.join(lines)


def main():
    SIZE = 20  # 20x20 fits 52 items in grid

    font, cmap, strike = load_font()
    print(f"Loaded NotoColorEmoji.ttf ({len(strike)} glyph bitmaps)", file=sys.stderr)

    out_dir = Path(__file__).parent.parent / 'src' / 'fonts' / 'emoji_images'
    out_dir.mkdir(parents=True, exist_ok=True)

    output_lines = [
        '// Auto-generated emoji images for LVGL picker',
        '// Generated by scripts/gen_emoji_images.py from NotoColorEmoji.ttf (CBDT table)',
        '#include <lvgl.h>',
        '',
    ]

    for i, emoji in enumerate(PICKER_EMOJI):
        name = f"emoji_img_{i}"
        cp = ord(emoji)

        bgra = extract_bitmap(cmap, strike, cp, SIZE)
        if bgra is None:
            print(f"  [{i+1}/{len(PICKER_EMOJI)}] {emoji} U+{cp:04X} — MISSING, using placeholder", file=sys.stderr)
            bgra = b'\x00' * (SIZE * SIZE * 4)
        else:
            print(f"  [{i+1}/{len(PICKER_EMOJI)}] {emoji} U+{cp:04X} ({len(bgra)} bytes)", file=sys.stderr)

        c_code = generate_lvgl_image_c(name, bgra, SIZE, SIZE)
        output_lines.append(c_code)

    # Write images header
    out_file = out_dir / 'emoji_picker_images.h'
    with open(out_file, 'w') as f:
        f.write('\n'.join(output_lines))
    print(f"\nWrote {out_file}", file=sys.stderr)

    # Write index header
    idx_lines = [
        '#ifndef EMOJI_PICKER_INDEX_H',
        '#define EMOJI_PICKER_INDEX_H',
        '#include <lvgl.h>',
        '#include "emoji_picker_images.h"',
        '',
        f'static constexpr int EMOJI_PICKER_IMG_COUNT = {len(PICKER_EMOJI)};',
        '',
        '// Extern declarations for all emoji images',
    ]
    for i in range(len(PICKER_EMOJI)):
        idx_lines.append(f'extern const lv_image_dsc_t emoji_img_{i};')

    idx_lines.extend([
        '',
        '// Array of all emoji image descriptors',
        'static const lv_image_dsc_t* emoji_picker_images[] = {',
    ])
    for i in range(len(PICKER_EMOJI)):
        idx_lines.append(f'    &emoji_img_{i},')
    idx_lines.extend([
        '};',
        '',
        '#endif',
    ])

    idx_file = out_dir / 'emoji_picker_index.h'
    with open(idx_file, 'w') as f:
        f.write('\n'.join(idx_lines))
    print(f"Wrote {idx_file}", file=sys.stderr)


if __name__ == '__main__':
    main()
