#!/usr/bin/env python3
"""Create or verify the reviewed PlatformIO resolved-package graph."""

from __future__ import annotations

import argparse
import difflib
import subprocess
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
LOCK_PATH = ROOT / "ci" / "platformio-packages.lock"
ENVIRONMENT = "SigurdOS_TDeck"


def run(*args: str) -> str:
    result = subprocess.run(
        args,
        cwd=ROOT,
        check=True,
        text=True,
        stdout=subprocess.PIPE,
    )
    return result.stdout.strip()


def resolved_graph(environment: str = ENVIRONMENT) -> str:
    core = run("pio", "--version")
    meshcore = run("git", "rev-parse", "HEAD:lib/meshcore")
    platform = run(
        "pio", "pkg", "list", "-e", environment, "--only-platforms"
    )
    libraries = run(
        "pio", "pkg", "list", "-e", environment, "--only-libraries"
    )
    return (
        "# Generated by scripts/platformio_lock.py; review diffs before updating.\n"
        f"{core}\n"
        f"MeshCore submodule @ {meshcore}\n\n"
        f"{platform}\n\n"
        f"{libraries}\n"
    )


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--check", action="store_true")
    mode.add_argument("--write", action="store_true")
    parser.add_argument(
        "--environment",
        default=ENVIRONMENT,
        help=f"PlatformIO environment to resolve (default: {ENVIRONMENT})",
    )
    return parser


def main() -> int:
    args = build_parser().parse_args()

    current = resolved_graph(args.environment)
    if args.write:
        LOCK_PATH.write_text(current, encoding="utf-8")
        return 0

    expected = LOCK_PATH.read_text(encoding="utf-8")
    if current == expected:
        return 0

    print(
        "".join(
            difflib.unified_diff(
                expected.splitlines(keepends=True),
                current.splitlines(keepends=True),
                fromfile=str(LOCK_PATH),
                tofile="resolved PlatformIO graph",
            )
        )
    )
    print("PlatformIO graph drifted; run scripts/platformio_lock.py --write")
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
